### ISSUE TITLE
model freeze in 

### ISSUE THREAD

**Issue by jdfoxito** [ashish4122/Text-Classification-using-NLP#1]
in next lines, model is freeze,

cv = CountVectorizer(max_features=20000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

**Comment by ashish4122** [comment]
That is because  of the large feature space and space usage .So either you can lower your max_features count  or you can avoid converting sparse matrix to a dense one and use it directly. This way the process will be much faster. Hope this helps.
